"""Export the winning architecture to a form the C inference code can run.

Three things happen here. Batch norm is folded into the convolution in front of
it, because a microcontroller should not spend cycles on an affine transform
that is constant at inference. The network is flattened into a list of ops with
every shape resolved, so the C side interprets a table instead of inferring
shapes. And a set of golden input and output pairs is written from the folded
PyTorch model, so the C implementation can be checked against it rather than
eyeballed.

The op table is generated by walking the genome the same way search.space.build
does. Hand transcribing an architecture into C is how the two drift apart.
"""
from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

import torch
import torch.nn as nn

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from search.blocks import AsymBlock, ShiftBlock  # noqa: E402
from search.space import build                   # noqa: E402

OUT = ROOT / "firmware" / "generated"

OP_CONV, OP_ACT, OP_SHIFT, OP_RES_SAVE, OP_RES_ADD, OP_POOL, OP_LINEAR = range(7)
OP_NAMES = ["CONV", "ACT", "SHIFT", "RES_SAVE", "RES_ADD", "POOL", "LINEAR"]


class Emitter:
    def __init__(self) -> None:
        self.ops: list[dict] = []
        self.weights: list[float] = []
        self.indices: list[int] = []

    def put_w(self, t: torch.Tensor) -> int:
        off = len(self.weights)
        self.weights.extend(t.detach().flatten().tolist())
        return off

    def put_idx(self, t: torch.Tensor) -> int:
        off = len(self.indices)
        self.indices.extend(int(v) for v in t.flatten())
        return off

    def op(self, kind: int, **kw) -> None:
        base = dict(op=kind, in_c=0, in_h=0, in_w=0, out_c=0, out_h=0, out_w=0,
                    kh=1, kw=1, sh=1, sw=1, ph=0, pw=0, groups=1,
                    w_off=-1, b_off=-1, extra=0)
        base.update(kw)
        self.ops.append(base)


def fold_bn(conv: nn.Conv2d, bn: nn.BatchNorm2d) -> tuple[torch.Tensor, torch.Tensor]:
    """w' = w * gamma/sqrt(var+eps), b' = beta - mean * gamma/sqrt(var+eps).

    Exact for a convolution with no bias followed by batch norm in eval mode,
    which is every conv and bn pair in this network.
    """
    s = bn.weight / torch.sqrt(bn.running_var + bn.eps)
    w = conv.weight * s.reshape(-1, 1, 1, 1)
    b = bn.bias - bn.running_mean * s
    return w, b


def emit_conv(e: Emitter, conv: nn.Conv2d, bn: nn.BatchNorm2d | None,
              c: int, h: int, w: int) -> tuple[int, int, int]:
    weight, bias = fold_bn(conv, bn) if bn is not None else (
        conv.weight, torch.zeros(conv.out_channels))
    kh, kw = conv.kernel_size
    sh, sw = conv.stride
    ph, pw = conv.padding
    oh = (h + 2 * ph - kh) // sh + 1
    ow = (w + 2 * pw - kw) // sw + 1
    e.op(OP_CONV, in_c=c, in_h=h, in_w=w, out_c=conv.out_channels, out_h=oh, out_w=ow,
         kh=kh, kw=kw, sh=sh, sw=sw, ph=ph, pw=pw, groups=conv.groups,
         w_off=e.put_w(weight), b_off=e.put_w(bias))
    return conv.out_channels, oh, ow


def emit(model: nn.Module, shift: int) -> Emitter:
    e = Emitter()
    c, h, w = 3, 32, 32

    stem_conv, stem_bn = model.stem[0], model.stem[1]
    c, h, w = emit_conv(e, stem_conv, stem_bn, c, h, w)
    e.op(OP_ACT, in_c=c, in_h=h, in_w=w, out_c=c, out_h=h, out_w=w, extra=shift)

    for block in model.blocks:
        in_c, in_h, in_w = c, h, w
        e.op(OP_RES_SAVE, in_c=in_c, in_h=in_h, in_w=in_w,
             out_c=in_c, out_h=in_h, out_w=in_w)

        if isinstance(block, AsymBlock):
            c, h, w = emit_conv(e, block.dw_h, None, c, h, w)
            c, h, w = emit_conv(e, block.dw_v, block.bn_dw, c, h, w)
            e.op(OP_ACT, in_c=c, in_h=h, in_w=w, out_c=c, out_h=h, out_w=w, extra=shift)
            c, h, w = emit_conv(e, block.pw, block.bn_pw, c, h, w)
            e.op(OP_ACT, in_c=c, in_h=h, in_w=w, out_c=c, out_h=h, out_w=w, extra=shift)
            stride = block.dw_v.stride[0]
        elif isinstance(block, ShiftBlock):
            e.op(OP_SHIFT, in_c=c, in_h=h, in_w=w, out_c=c, out_h=h, out_w=w,
                 extra=c // 5)
            c, h, w = emit_conv(e, block.pw, block.bn, c, h, w)
            e.op(OP_ACT, in_c=c, in_h=h, in_w=w, out_c=c, out_h=h, out_w=w, extra=shift)
            stride = block.pw.stride[0]
        else:
            raise TypeError(type(block))

        # The index map is emitted rather than recomputed in C. torch rounds
        # halves to even and C rounds them away from zero, so a linspace
        # recomputed on the other side would disagree on exactly the ties.
        e.op(OP_RES_ADD, in_c=in_c, in_h=in_h, in_w=in_w, out_c=c, out_h=h, out_w=w,
             sh=stride, sw=stride, extra=e.put_idx(block.res.idx))

    e.op(OP_POOL, in_c=c, in_h=h, in_w=w, out_c=c, out_h=1, out_w=1)
    head = model.head
    e.op(OP_LINEAR, in_c=c, in_h=1, in_w=1, out_c=head.out_features, out_h=1, out_w=1,
         w_off=e.put_w(head.weight), b_off=e.put_w(head.bias))
    return e


def write_header(e: Emitter, path: Path, n_golden: int) -> None:
    fields = ["op", "in_c", "in_h", "in_w", "out_c", "out_h", "out_w", "kh", "kw",
              "sh", "sw", "ph", "pw", "groups", "w_off", "b_off", "extra"]
    peak = max(max(o["in_c"] * o["in_h"] * o["in_w"],
                   o["out_c"] * o["out_h"] * o["out_w"]) for o in e.ops)
    lines = [
        "/* Generated by export/export_c.py. Do not edit: regenerate it. */",
        "#ifndef MICRONET_ARCH_H",
        "#define MICRONET_ARCH_H",
        "",
        f"#define MICRONET_N_OPS     {len(e.ops)}",
        f"#define MICRONET_N_WEIGHTS {len(e.weights)}",
        f"#define MICRONET_N_INDICES {len(e.indices)}",
        f"#define MICRONET_PEAK      {peak}",
        f"#define MICRONET_CLASSES   {e.ops[-1]['out_c']}",
        f"#define MICRONET_N_GOLDEN  {n_golden}",
        "",
        "enum { " + ", ".join(f"OP_{n}" for n in OP_NAMES) + " };",
        "",
        "typedef struct {",
        "    int " + ", ".join(fields) + ";",
        "} MicroOp;",
        "",
        "static const MicroOp MICRONET_OPS[MICRONET_N_OPS] = {",
    ]
    for o in e.ops:
        vals = ", ".join(f"{o[f]:>6d}" for f in fields)
        lines.append(f"    {{ {vals} }},   /* {OP_NAMES[o['op']]} */")
    lines += ["};", "", "#endif"]
    path.write_text("\n".join(lines) + "\n")


@torch.no_grad()
def _act_inputs(model: nn.Module, x: torch.Tensor) -> list[torch.Tensor]:
    """Inputs to every activation, which is what decides whether the ReLU6
    ceiling is reached. Hooking the output instead reports nothing, since the
    output is clamped at 6 by construction and can never exceed it."""
    from search.blocks import PowerOfTwoReLU

    seen: list[torch.Tensor] = []
    handles = [m.register_forward_hook(lambda _m, i, _o: seen.append(i[0]))
               for m in model.modules() if isinstance(m, PowerOfTwoReLU)]
    model(x)
    for h in handles:
        h.remove()
    return seen


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", default="results/winner.pt")
    p.add_argument("--golden", type=int, default=8)
    p.add_argument("--seed", type=int, default=0)
    a = p.parse_args()

    ckpt_path = ROOT / a.checkpoint
    if ckpt_path.exists():
        ckpt = torch.load(ckpt_path, weights_only=False)
        genome, state, src = ckpt["genome"], ckpt["state_dict"], a.checkpoint
    else:
        genome = json.loads((ROOT / "results" / "best_genome.json").read_text())
        state, src = None, f"seed {a.seed} initialisation, no checkpoint found"

    torch.manual_seed(a.seed)
    model = build(genome)
    if state is not None:
        model.load_state_dict(state)
    model.eval()

    e = emit(model, genome["act_shift"])
    OUT.mkdir(parents=True, exist_ok=True)

    (OUT / "micronet_weights.bin").write_bytes(
        struct.pack(f"<{len(e.weights)}f", *e.weights))
    (OUT / "micronet_indices.bin").write_bytes(
        struct.pack(f"<{len(e.indices)}i", *e.indices))

    # Half the golden inputs are at the scale of a normalised CIFAR image and
    # half are deliberately larger. Without the large ones no activation in an
    # untrained network ever reaches the ReLU6 ceiling, so deleting the clamp
    # from the C would pass the equivalence test. Checked: it does not now.
    torch.manual_seed(a.seed + 999)
    half = a.golden // 2
    x = torch.cat([torch.randn(a.golden - half, 3, 32, 32),
                   torch.randn(half, 3, 32, 32) * 12.0])
    with torch.no_grad():
        y = model(x)
    acts = _act_inputs(model, x)
    hit = sum(int((t > 6.0).any()) for t in acts)
    frac = sum(float((t > 6.0).float().mean()) for t in acts) / max(len(acts), 1)
    print(f"ReLU6 ceiling coverage: {hit} of {len(acts)} activations saturate "
          f"somewhere, {100 * frac:.1f}% of values clamped on average")
    if hit == 0:
        raise SystemExit("golden set does not exercise the clamp; the C could "
                         "drop it and still pass")
    (OUT / "micronet_golden.bin").write_bytes(
        struct.pack(f"<{x.numel()}f", *x.flatten().tolist())
        + struct.pack(f"<{y.numel()}f", *y.flatten().tolist()))

    write_header(e, OUT / "micronet_arch.h", a.golden)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"source          : {src}")
    print(f"ops             : {len(e.ops)}")
    print(f"weights folded  : {len(e.weights):,} floats "
          f"(model has {n_params:,} parameters before folding)")
    print(f"residual indices: {len(e.indices)}")
    print(f"golden pairs    : {a.golden}")
    for f in sorted(OUT.iterdir()):
        print(f"  {f.relative_to(ROOT)}  {f.stat().st_size / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
